# Generated by Django 2.0.4 on 2018-04-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='')),
                ('content', models.TextField(verbose_name='')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='')),
                ('update_date', models.DateField(auto_now=True, null=True, verbose_name='')),
            ],
        ),
    ]
